return {
	UnlockCode = "3736",
	MaximumFailedAttempts = 5,
	AttemptWindowSeconds = 30,
	LockoutSeconds = 60,
	ActionCooldown = 0.2,
	SpawnCooldown = 1,
	SpeedPresets = {
		Normal = 36,
		Boost = 60,
		Extreme = 90,
	},
	MaximumWalkSpeed = 100,
	DamageBoostMultiplier = 2,
	MaximumDamageMultiplier = 3,
	DamageBoostSeconds = 60,
	AllowedEnemyTypes = {
		Basic = true,
		Fast = true,
		Tank = true,
		Boss = true,
		FireImp = true,
		LavaGolem = true,
		FrostWolf = true,
		IceGolem = true,
		StormWolf = true,
		StormOrc = true,
		StoneWarrior = true,
		EarthGolem = true,
		AshwingDrake = true,
		RiftDragon = true,
		NullHunter = true,
		LabyrinthHorror = true,
		OrcChampion = true,
		ShinyChicken = true,
		LavaTitan = true,
		FrostGiant = true,
		StormColossus = true,
		MountainGuardian = true,
		PrismaticOverlord = true,
	},
}
