-- Stable gameplay IDs resolve to optional presentation profiles. A nil AssetId intentionally uses procedural fallback art.
return {
	Version = 1,
	Weapons = {
		IronBlade = {ModelId = "BasicSwordModel01", AssetId = nil, Fallback = "Blade"},
		DawnsteelSword = {ModelId = "DawnsteelSwordModel01", AssetId = nil, Fallback = "Blade"},
		SkyglassKatana = {ModelId = "SkyglassKatanaModel01", AssetId = nil, Fallback = "Katana"},
		RiftwindKatana = {ModelId = "RiftwindKatanaModel01", AssetId = nil, Fallback = "Katana"},
		CelestialLightblade = {ModelId = "CelestialLightbladeModel01", AssetId = nil, Fallback = "Greatsword"},
		SolarChaingun = {ModelId = "SolarChaingunModel01", AssetId = nil, Fallback = "Rifle"},
		EmberRepeater = {ModelId = "EmberRepeaterModel01", AssetId = nil, Fallback = "Rifle"},
		FrostPistol = {ModelId = "FrostPistolModel01", AssetId = nil, Fallback = "Sidearm"},
		TempestLaser = {ModelId = "TempestLaserModel01", AssetId = nil, Fallback = "Rifle"},
		StonehandCannon = {ModelId = "StonehandCannonModel01", AssetId = nil, Fallback = "Sidearm"},
		GaleFamas = {ModelId = "GaleFamasModel01", AssetId = nil, Fallback = "Rifle"},
		RiftBlaster = {ModelId = "RiftBlasterModel01", AssetId = nil, Fallback = "Sidearm"},
		ArsenalRelic = {ModelId = "ArsenalRelicModel01", AssetId = nil, Fallback = "Rifle"},
		BlademasterArsenal = {ModelId = "BlademasterArsenalModel01", AssetId = nil, Fallback = "Greatsword"},
		ThunderKatana = {ModelId = "ThunderKatanaModel01", AssetId = nil, Fallback = "Katana"},
		InfernoSword = {ModelId = "InfernoSwordModel01", AssetId = nil, Fallback = "Greatsword"},
		FrostSpear = {ModelId = "FrostSpearModel01", AssetId = nil, Fallback = "Spear"},
		Earthbreaker = {ModelId = "EarthbreakerModel01", AssetId = nil, Fallback = "Hammer"},
		GravityHammer = {ModelId = "GravityHammerModel01", AssetId = nil, Fallback = "Hammer"},
		StormRifle = {ModelId = "StormRifleModel01", AssetId = nil, Fallback = "Rifle"},
		VoidStaff = {ModelId = "VoidStaffModel01", AssetId = nil, Fallback = "Staff"},
	},
	Transformations = {
		Wolf = {ModelId = "WolfModel01", AssetId = nil, Fallback = "AvatarMorph"},
		Bear = {ModelId = "BearModel01", AssetId = nil, Fallback = "AvatarMorph"},
		Eagle = {ModelId = "EagleModel01", AssetId = nil, Fallback = "AvatarMorph"},
	},
	Enemies = {
		FireImp = {ModelId = "FireImpModel01", Fallback = "Runner"},
		FrostWolf = {ModelId = "FrostWolfModel01", Fallback = "Runner"},
		ThunderWolf = {ModelId = "ThunderWolfModel01", Fallback = "Runner"},
		IronGolem = {ModelId = "IronGolemModel01", Fallback = "Tank"},
		LavaGolem = {ModelId = "LavaGolemModel01", Fallback = "Tank"},
		Orc = {ModelId = "OrcModel01", Fallback = "Warrior"},
		OrcSmasher = {ModelId = "OrcSmasherModel01", Fallback = "Tank"},
		OrcArcher = {ModelId = "OrcArcherModel01", Fallback = "Ranged"},
		AshwingDrake = {ModelId = "AshwingDrakeModel01", Fallback = "Ranged"},
		RiftDragon = {ModelId = "RiftDragonModel01", Fallback = "Ranged"},
		NullHunter = {ModelId = "NullHunterModel01", Fallback = "Runner"},
		LabyrinthHorror = {ModelId = "LabyrinthHorrorModel01", Fallback = "Tank"},
		OrcWarrior = {ModelId = "OrcWarriorModel01", Fallback = "Warrior"},
	},
	Effects = {
		Fire = {EffectProfile = "FireBurst01"}, Ice = {EffectProfile = "FrostBurst01"},
		Lightning = {EffectProfile = "SegmentedLightning01"}, Earth = {EffectProfile = "RockImpact01"},
		Gravity = {EffectProfile = "GravityDistortion01"},
	},
}
