return {
	RarityOrder = {Common = 1, Uncommon = 2, Rare = 3, Epic = 4, Legendary = 5},
	RarityColors = {
		Common = Color3.fromRGB(190, 200, 215), Uncommon = Color3.fromRGB(95, 225, 135),
		Rare = Color3.fromRGB(75, 155, 255), Epic = Color3.fromRGB(185, 95, 255), Legendary = Color3.fromRGB(255, 180, 55),
	},
	Capacity = 40,
	Items = {
		IronBlade = {DisplayName = "Iron Blade", Category = "Weapon", Rarity = "Common", MaximumStack = 1, BuyPrice = 250, EquipSlot = "Weapon", Description = "A dependable ascendant-forged starter sword.", Stats = {Attack = 5}, WeaponColor = Color3.fromRGB(185, 205, 225), WeaponSize = Vector3.new(0.3, 4.2, 0.65)},
		StormFang = {DisplayName = "Storm Fang", Category = "Weapon", Rarity = "Rare", MaximumStack = 1, BuyPrice = 2500, EquipSlot = "Weapon", Description = "A charged blade recovered from elite Rift creatures.", Stats = {Attack = 18, CriticalChance = 0.05, Power = 8}, WeaponColor = Color3.fromRGB(80, 205, 255), WeaponSize = Vector3.new(0.35, 4.8, 0.75)},
		Starbreaker = {DisplayName = "Starbreaker", Category = "Weapon", Rarity = "Legendary", MaximumStack = 1, EquipSlot = "Weapon", Description = "A boss-forged greatblade humming with collapsed starlight.", Stats = {Attack = 42, CriticalChance = 0.1, CriticalDamage = 0.35, Power = 20}, WeaponColor = Color3.fromRGB(255, 185, 70), WeaponSize = Vector3.new(0.55, 6.2, 1)},
		GravityHammer = {DisplayName = "Gravity Hammer", Category = "Weapon", Rarity = "Epic", MaximumStack = 1, EquipSlot = "Weapon", Description = "A crushing weapon wrapped in violet gravity fields.", Stats = {Attack = 30, Defense = 8, Power = 12}, WeaponColor = Color3.fromRGB(145, 80, 235), WeaponSize = Vector3.new(0.8, 5.2, 1.2)},
		EmberGreatsword = {DisplayName = "Ember Greatsword", Category = "Weapon", Rarity = "Epic", MaximumStack = 1, EquipSlot = "Weapon", Description = "A broad blade forged around an eternal ember.", Stats = {Attack = 34, CriticalDamage = 0.25}, WeaponColor = Color3.fromRGB(255, 90, 45), WeaponSize = Vector3.new(0.6, 5.8, 1.1)},
		CelestialSpear = {DisplayName = "Celestial Spear", Category = "Weapon", Rarity = "Legendary", MaximumStack = 1, EquipSlot = "Weapon", Description = "A luminous polearm made for evolved warriors.", Stats = {Attack = 38, Power = 30, CriticalChance = 0.08}, WeaponColor = Color3.fromRGB(255, 225, 110), WeaponSize = Vector3.new(0.28, 6.5, 0.55)},
		IronGuard = {DisplayName = "Iron Guard", Category = "Armor", Rarity = "Uncommon", MaximumStack = 1, BuyPrice = 800, EquipSlot = "Chest", Description = "Layered fort armor that softens incoming attacks.", Stats = {Health = 35, Defense = 8}},
		GaleBoots = {DisplayName = "Gale Boots", Category = "Armor", Rarity = "Rare", MaximumStack = 1, BuyPrice = 1200, EquipSlot = "Boots", Description = "Light boots that convert motion into momentum.", Stats = {Health = 10, Speed = 5}},
		RiftHelm = {DisplayName = "Rift Helm", Category = "Armor", Rarity = "Rare", MaximumStack = 1, BuyPrice = 1400, EquipSlot = "Head", Description = "A sealed helm that protects the mind from Rift pressure.", Stats = {Health = 25, Defense = 10, MP = 10}},
		TitanGloves = {DisplayName = "Titan Gloves", Category = "Armor", Rarity = "Epic", MaximumStack = 1, EquipSlot = "Gloves", Description = "Heavy gauntlets that turn defense into striking power.", Stats = {Attack = 12, Defense = 12}},
		StormCore = {DisplayName = "Storm Core", Category = "Artifact", Rarity = "Epic", MaximumStack = 1, EquipSlot = "Artifact", Description = "An unstable core that amplifies power and critical strikes.", Stats = {Power = 18, CriticalChance = 0.08, MP = 20}},
		TitanHeart = {DisplayName = "Titan Heart", Category = "Artifact", Rarity = "Legendary", MaximumStack = 1, EquipSlot = "Artifact", Description = "A dense living crystal that greatly reinforces its bearer.", Stats = {Health = 90, Defense = 15}},
		HealthPotion = {DisplayName = "Health Core", Category = "Consumable", Rarity = "Common", MaximumStack = 99, BuyPrice = 60, Description = "Restores 45 health.", Consumable = {Kind = "Health", Amount = 45, Cooldown = 8}},
		ManaPotion = {DisplayName = "Mana Crystal", Category = "Consumable", Rarity = "Common", MaximumStack = 99, BuyPrice = 70, Description = "Restores 40 MP.", Consumable = {Kind = "MP", Amount = 40, Cooldown = 8}},
		BattleSerum = {DisplayName = "Battle Serum", Category = "Consumable", Rarity = "Rare", MaximumStack = 20, BuyPrice = 300, Description = "Increases all damage by 25% for 60 seconds.", Consumable = {Kind = "DamageBuff", Multiplier = 1.25, Duration = 60, Cooldown = 30}},
		StoneSkinTonic = {DisplayName = "Stone Skin Tonic", Category = "Consumable", Rarity = "Rare", MaximumStack = 20, BuyPrice = 275, Description = "Adds 25 defense for 60 seconds.", Consumable = {Kind = "DefenseBuff", Amount = 25, Duration = 60, Cooldown = 30}},
		EnergySurge = {DisplayName = "Energy Surge", Category = "Consumable", Rarity = "Uncommon", MaximumStack = 20, BuyPrice = 180, Description = "Adds 8 MP regeneration per second for 45 seconds.", Consumable = {Kind = "RegenBuff", Amount = 8, Duration = 45, Cooldown = 25}},
		EvolutionShard = {DisplayName = "Evolution Shard", Category = "Material", Rarity = "Uncommon", MaximumStack = 99, Description = "Condensed evolution matter used in advanced crafting."},
		RiftCrystal = {DisplayName = "Rift Crystal", Category = "Material", Rarity = "Rare", MaximumStack = 99, Description = "A crystalline fragment left by elite enemies."},
		BossCore = {DisplayName = "Boss Core", Category = "Material", Rarity = "Epic", MaximumStack = 99, Description = "A guaranteed trophy from a defeated wave boss."},
	},
	Recipes = {
		HealthPotion = {Quantity = 2, Ingredients = {EvolutionShard = 2}},
		BattleSerum = {Quantity = 1, Ingredients = {EvolutionShard = 4, RiftCrystal = 1}},
		StormFang = {Quantity = 1, Ingredients = {EvolutionShard = 12, RiftCrystal = 5}},
		IronGuard = {Quantity = 1, Ingredients = {EvolutionShard = 8}},
	},
	LootTables = {
		Basic = {{ItemId = "HealthPotion", Weight = 16}, {ItemId = "EvolutionShard", Weight = 8}},
		Fast = {{ItemId = "ManaPotion", Weight = 18}, {ItemId = "EvolutionShard", Weight = 10}},
		Tank = {{ItemId = "IronGuard", Weight = 3}, {ItemId = "EvolutionShard", Weight = 25}, {ItemId = "RiftCrystal", Weight = 8}},
		Elite = {{ItemId = "StormFang", Weight = 3}, {ItemId = "RiftCrystal", Weight = 35}, {ItemId = "BattleSerum", Weight = 12}},
		Boss = {{ItemId = "Starbreaker", Weight = 2}, {ItemId = "StormCore", Weight = 8}, {ItemId = "TitanHeart", Weight = 4}},
	},
}
