return {
	StartingLevel = 1,
	StartingXP = 0,
	StartingCoins = 0,
	StartingAttack = 25,
	StartingMaxHealth = 100,
	XPBase = 100,
	XPExponent = 1.45,
	LevelHealthBonus = 10,
	LevelAttackBonus = 3,
	MeleeRange = 11,
	MeleeDamage = 25,
	MeleeCooldown = 0.45,
	MeleeComboReset = 1.1,
	MeleeCombo = {
		{DamageMultiplier = 1, Cooldown = 0.34, Stun = 0.12, Knockback = 5},
		{DamageMultiplier = 1.05, Cooldown = 0.34, Stun = 0.14, Knockback = 6},
		{DamageMultiplier = 1.15, Cooldown = 0.4, Stun = 0.18, Knockback = 8},
		{DamageMultiplier = 1.6, Cooldown = 0.72, Stun = 0.5, Knockback = 42},
	},
	StunImmunitySeconds = 0.3,
	PerfectBlockRearm = 0.5,
	Abilities = {
		EnergyBolt = {
			DisplayName = "Energy Bolt",
			Description = "Launch a fast energy projectile that detonates on impact.",
			RequiredLevel = 1,
			RequiredEvolution = 0,
			CastType = "Projectile",
			Targeting = "Point",
			Cooldown = 2,
			EnergyCost = 10,
			Damage = 50,
			Range = 80,
			Radius = 4,
			ProjectileSpeed = 115,
		},
		EnergyBurst = {
			DisplayName = "Energy Burst",
			Description = "Release a radial blast that throws enemies away.",
			RequiredLevel = 3,
			RequiredEvolution = 0,
			CastType = "Radial",
			Targeting = "Self",
			Cooldown = 6,
			EnergyCost = 25,
			Damage = 70,
			Range = 60,
			Radius = 14,
			Knockback = 45,
		},
		EnergyBeam = {
			DisplayName = "Energy Beam", Description = "Fire a piercing beam through every enemy in its path.",
			CastType = "Beam", Targeting = "Point", RequiredLevel = 8, RequiredEvolution = 1,
			Cooldown = 8, EnergyCost = 30, Damage = 115, Range = 105, Radius = 4,
		},
		GravityPulse = {
			DisplayName = "Gravity Pulse", Description = "Collapse nearby space and drag enemies toward you.",
			CastType = "Gravity", Targeting = "Self", RequiredLevel = 15, RequiredEvolution = 1,
			Cooldown = 10, EnergyCost = 35, Damage = 85, Range = 60, Radius = 20, PullStrength = 58,
		},
		ChainLightning = {
			DisplayName = "Chain Lightning", Description = "Arc through a group, seeking new targets after every strike.",
			CastType = "Chain", Targeting = "Point", RequiredLevel = 25, RequiredEvolution = 2,
			Cooldown = 12, EnergyCost = 45, Damage = 100, Range = 75, Radius = 5, ChainRange = 24, MaximumChains = 6,
		},
		Tornado = {
			DisplayName = "Rift Tornado", Description = "Summon a violent vortex that lifts and spins monsters in its wake.",
			CastType = "Tornado", Targeting = "Point", RequiredLevel = 35, RequiredEvolution = 2,
			Cooldown = 16, EnergyCost = 55, Damage = 72, Range = 85, Radius = 16, Duration = 4,
			TickInterval = 0.5, PullStrength = 70, ProjectileSpeed = 42,
		},
	},
	Mastery = {
		MaximumLevel = 10,
		XPPerDamage = 0.04,
		XPPerCast = 2,
		DamagePerLevel = 0.04,
		CostReductionPerLevel = 0.015,
		XPBase = 30,
	},
}
