return {
	CompletionBaseXP = 25,
	CompletionXPPerWave = 12,
	CompletionBaseGold = 15,
	CompletionGoldPerWave = 6,
	EliteStartWave = 3,
	EliteBaseChance = 0.08,
	EliteChancePerWave = 0.015,
	EliteMaximumChance = 0.32,
	BossParticipationMinimum = 0.03,
	BossRewardWaveMultiplier = 0.08,
	EliteModifiers = {
		Giant = {
			HealthMultiplier = 1.8,
			DamageMultiplier = 1.3,
			SpeedMultiplier = 0.88,
			RewardMultiplier = 2,
			Scale = 1.28,
			Color = Color3.fromRGB(255, 120, 75),
		},
		Haste = {
			HealthMultiplier = 1.15,
			DamageMultiplier = 1.15,
			SpeedMultiplier = 1.42,
			RewardMultiplier = 1.75,
			Color = Color3.fromRGB(255, 235, 80),
		},
		Fortified = {
			HealthMultiplier = 1.55,
			DamageMultiplier = 1.1,
			SpeedMultiplier = 0.95,
			DamageTakenMultiplier = 0.72,
			RewardMultiplier = 2.25,
			Color = Color3.fromRGB(155, 120, 255),
		},
	},
	BossPhases = {
		{
			Phase = 2,
			HealthThreshold = 0.65,
			SpeedMultiplier = 1.12,
			DamageMultiplier = 1.2,
			AttackCooldownMultiplier = 0.82,
			SlamInterval = 8,
		},
		{
			Phase = 3,
			HealthThreshold = 0.3,
			SpeedMultiplier = 1.28,
			DamageMultiplier = 1.45,
			AttackCooldownMultiplier = 0.62,
			SlamInterval = 5,
		},
	},
	BossSlamRadius = 22,
	BossSlamWindup = 0.9,
	BossSlamDamageMultiplier = 1.1,
	BossArchetypes = {
		{Id = "Stone", DisplayName = "Stone Destroyer", Color = Color3.fromRGB(255, 100, 75)},
		{Id = "Rift", DisplayName = "Rift Tyrant", Color = Color3.fromRGB(175, 75, 255)},
		{Id = "Storm", DisplayName = "Storm Colossus", Color = Color3.fromRGB(75, 190, 255)},
	},
	BossSpecialInterval = 7,
	BossVortexRadius = 28,
	BossVortexWindup = 1.15,
	BossVortexDamageMultiplier = 0.8,
	BossLightningRadius = 8,
	BossLightningWindup = 0.85,
	BossLightningDamageMultiplier = 1.25,
}
